default_stages: [commit, push]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-ast
      - id: check-json
      - id: check-yaml
      - id: trailing-whitespace
        exclude: 'README.md'
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: ['--maxkb=50000']
      - id: check-merge-conflict
      - id: check-docstring-first
      - id: double-quote-string-fixer

  - repo: https://github.com/pycqa/isort
    rev: 5.11.5
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.6.0
    hooks:
      - id: autopep8
        args: [--in-place]
