volumes:
  redis_data:
  postgres_data:
  flower_data_prod:

x-app: &app
  env_file:
    - ./.env
  restart: always

# TODO: django, nginx, celery

services:
  redis:
    <<: *app
    image: redis:6.0.8-alpine
    volumes:
      - redis_data:/data
    ports:
      - ${DOCKER_REDIS_PORT:-6379}:6379

  postgres:
    <<: *app
    image: postgres:12.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - ${DOCKER_POSTGRES_PORT:-5432}:5432

  flower:
    <<: *app
    image: mher/flower:2.0
    command: celery flower
    volumes:
      - flower_data_prod:/data
    ports:
      - ${DOCKER_FLOWER_PORT:-5555}:5555
    depends_on:
      - redis
