# Generated by Django 4.2.10 on 2024-03-09 10:36

import django.core.validators
from django.db import migrations, models

import app.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recognition',
            name='task_id',
            field=models.CharField(blank=True, max_length=36, verbose_name='celery задача'),
        ),
        migrations.AlterField(
            model_name='recognition',
            name='recognized_file',
            field=models.FileField(blank=True, null=True, upload_to=app.models.upload_recognized_video_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])], verbose_name='распознанный файл'),
        ),
    ]
