# Generated by Django 4.2.10 on 2024-03-14 12:23

import django.core.validators
from django.db import migrations, models

import app.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_recognition_task_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recognition',
            name='output_file',
            field=models.FileField(blank=True, null=True, upload_to=app.models.upload_output_file_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt'])], verbose_name='вывод команды распознавания'),
        ),
        migrations.AddField(
            model_name='recognition',
            name='stat_graph',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.upload_stat_graph_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg'])], verbose_name='график кол-ва действий'),
        ),
        migrations.AddField(
            model_name='recognition',
            name='stat_pie_chart',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.upload_stat_pie_chart_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg'])], verbose_name='круговая диаграмма'),
        ),
        migrations.AlterField(
            model_name='recognition',
            name='recognized_file',
            field=models.FileField(blank=True, null=True, upload_to=app.models.upload_recognized_video_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])], verbose_name='распознанный видео файл'),
        ),
    ]
